name: Build Debug APK

# Workflow wird manuell ausgelöst, ohne Versionsaktualisierung
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        
      - name: Get APK path
        id: apk-path
        run: |
          APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          echo "APK-Pfad: $APK_PATH"
          echo "path=$APK_PATH" >> $GITHUB_OUTPUT
          
      - name: Upload Debug APK as artifact
        uses: actions/upload-artifact@v1
        with:
          name: debug-apk
          path: ${{ steps.apk-path.outputs.path }}